### Practica 2 Bloque 4
Lara Ocón Madrid - 202115710

In [2]:
# Para este practica vamos a crear un excel con un reporte ejecutivo de la pizzeria Maven Pizzas
# Para ello, empleamos la libreria openpyxl

In [3]:
import pandas as pd
import openpyxl

In [5]:
df_pizzas_semana = pd.read_csv('ficheros_csv/pizzas_semana.csv')
df_pizzas_semana.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
Unnamed: 0,bbq_ckn,cali_ckn,ckn_alfredo,ckn_pesto,southw_ckn,thai_ckn,big_meat,classic_dlx,hawaiian,ital_cpcllo,...,spinach_supr,five_cheese,four_cheese,green_garden,ital_veggie,mediterraneo,mexicana,spin_pesto,spinach_fet,veggie_veg
semana 0,29.0,12.5,2.5,10.5,19.0,25.0,12.0,23.0,18.0,17.0,...,13.0,18.0,14.5,6.5,7.5,7.0,19.5,6.0,8.0,11.5
semana 1,58.0,65.0,49.0,28.5,38.5,64.0,34.0,63.5,63.5,33.5,...,27.0,60.0,64.0,24.0,27.0,19.5,37.0,28.0,43.0,38.5
semana 2,61.5,55.0,15.5,27.0,68.5,58.5,22.0,46.0,42.0,30.5,...,26.0,54.0,47.5,13.0,22.0,19.5,47.0,29.5,45.5,45.5
semana 3,73.5,83.0,22.0,25.0,36.5,65.5,35.0,49.0,60.0,34.5,...,18.0,58.0,68.5,20.0,36.5,25.5,34.5,20.0,37.0,42.0

In [12]:
# vamos a crear una tabla pivote que muestre la resta de ingredientes necesitados y predichos
df_concat = pd.concat([df_ingredientes_semana, df_predicciones], axis=0)
df_concat = df_concat.iloc[-1] - df_concat.iloc[:-1]
tabla_diferencia = df_concat.pivot_table(indes=df_concat.index, columns=df_ingredientes_semana.values, aggfunc='sum')

TypeError: unsupported operand type(s) for -: 'str' and 'str'